#!/bin/bash

# check for certain programs
if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.'
  echo 'Please run `brew install jq`'
  exit 1
fi

git checkout master || exit 1
git pull --rebase origin master || exit 1

# get current package version
version=$(jq '.version' package.json -r)

# create branch (update-changelog-${version})
branch_name="update-changelog-${version}"
git checkout -b ${branch_name}

# open CHANGELOG.md in vim; optionally prepopulate changelog and open to verify changes
current_date=$(date +%F)
sed -i -e '/## \[Unreleased\]/a \
\
[INSERT_NEW_ENTRY_HERE] \
' CHANGELOG.md
sed -i -e "s/\[INSERT_NEW_ENTRY_HERE\]/## \[${version}\] - ${current_date}/1" CHANGELOG.md

# commit changes and push up branch
git add .
git commit -m "Update changelog for v${version} release"
git push -u origin ${branch_name}

# open PR creation page in browser
open https://github.com/jasondippel/react-hoc-theme/compare/${branch_name}\?expand\=1
