import {
  VALUES as LIGHT_THEME_VALUES,
  VERSION as LIGHT_THEME_VERSION,
  TYPE as LIGHT_THEME_TYPE,
} from './lightTheme'
import {
  VALUES as DARK_THEME_VALUES,
  VERSION as DARK_THEME_VERSION,
  TYPE as DARK_THEME_TYPE,
} from './darkTheme'
import { DEPRECATED_FIELDS } from './deprecated'

const THEME_UPDATE_EVENT = 'THEME_UPDATE_EVENT'
const LS_KEY = '__O.0__::react-hoc-theme::'

const LIGHT_THEME = {
  type: LIGHT_THEME_TYPE,
  version: LIGHT_THEME_VERSION,
  values: LIGHT_THEME_VALUES,
}

const DARK_THEME = {
  type: DARK_THEME_TYPE,
  version: DARK_THEME_VERSION,
  values: DARK_THEME_VALUES,
}

const DEFAULT_THEME = LIGHT_THEME

export {
  LS_KEY,
  DEPRECATED_FIELDS,
  THEME_UPDATE_EVENT,
  DEFAULT_THEME,
  LIGHT_THEME,
  DARK_THEME,
}
