import {
  VALUES as LIGHT_THEME_VALUES,
  VERSION as LIGHT_THEME_VERSION,
  TYPE as LIGHT_THEME_TYPE,
} from './lightTheme'
import {
  VALUES as DARK_THEME_VALUES,
  VERSION as DARK_THEME_VERSION,
  TYPE as DARK_THEME_TYPE,
} from './darkTheme'

const THEME_UPDATE_EVENT = 'THEME_UPDATE_EVENT'

const LIGHT_THEME = {
  type: LIGHT_THEME_TYPE,
  version: LIGHT_THEME_VERSION,
  values: LIGHT_THEME_VALUES,
}

const DARK_THEME = {
  type: DARK_THEME_TYPE,
  version: DARK_THEME_VERSION,
  values: DARK_THEME_VALUES,
}

const DEFAULT_THEME = LIGHT_THEME
const DEFAULT_THEME_VALUES = LIGHT_THEME_VALUES
const DEFAULT_THEME_VERSION = LIGHT_THEME_VERSION
const DEFAULT_THEME_TYPE = 'default'

export {
  THEME_UPDATE_EVENT,
  // default theme
  DEFAULT_THEME,
  DEFAULT_THEME_VALUES,
  DEFAULT_THEME_TYPE,
  DEFAULT_THEME_VERSION,
  // light theme
  LIGHT_THEME,
  LIGHT_THEME_VALUES,
  LIGHT_THEME_TYPE,
  LIGHT_THEME_VERSION,
  // dark theme
  DARK_THEME,
  DARK_THEME_VALUES,
  DARK_THEME_TYPE,
  DARK_THEME_VERSION,
}
